### ISSUE TITLE
добавить метод Поля

### ISSUE THREAD

**Issue by sulfur17** [KalyakinAG/query-model#2]
предлагаю идею, вместо 
.Поле("Договор").Поле("Владелец").Поле("ИНН", "ИННКонтрагента")
.Поле("Договор").Поле("Сотрудник", "Сотрудник")
было бы проще писать
.Поля("Контрагент.Владелец.ИНН КАК ИННКонтрагента"
          |Договор.Сотрудник КАК Сотрудник");

**Comment by KalyakinAG** [comment]
Предлагаю придерживаться следующего стиля:
```
    .Поле("Договор")
    .Поле("Владелец")
    .Поле("ИНН", "ИННКонтрагента")
    .Поле("Договор")
    .Поле("Сотрудник", "Сотрудник")
;
```
Если речь идет о всех полях или полях одного какого-то источника, то можно использовать вариант со "\*":
```
    .Поле("*")
    .Поле("Контрагенты.*")
```
Идея добавить оператор множественного добавления полей меня периодически посещает, но я пока не нашел приемлемый вариант. Код должен выглядеть ненагруженным, операторы не должны дублировать функциональность, параметры операторов должны быть простыми. Конечно это субъективно, но предложенный Вами вариант выглядит тяжело :)

**Comment by sulfur17** [comment]
тогда отменяю задачу, спасибо за ответ)
